### ISSUE TITLE
Add CHANGELOG and create releases

### ISSUE THREAD

**Issue by milmazz** [devonestes/assertions#6]
Hey @devonestes, I hope you're doing well and thanks for maintaining this amazing helper. After a recent upgrade to `0.14.1`, `assertions` catch some errors (which is nice) on a few unit tests, at first I was confused because the whole suite was working correctly before, anyway, I tried finding the `CHANGELOG` file to read more information about recent changes, I didn't find that file for reference, then I tried looking at your [release](https://github.com/devonestes/assertions/releases) page, nothing there too. Then I checked the commit logs and finally found that you recently fixed the `assert_map_in_list/3` function, from there was easy to know why the test suite was failing.

So, my suggestion is to include a `CHANGELOG` file in the project, here you can find more information why [keeping a CHANGELOG file is important](https://keepachangelog.com/en/1.0.0/), and for every release put some information about the changes on that release. Another benefit from doing this is that bots like _dependabot_ (which now we use on the team) parses that information, here you can find an example from the `sentry` package:

![Screen Shot 2019-06-13 at 5 24 47 PM](https://user-images.githubusercontent.com/34700/59471250-2f868500-8e00-11e9-9c5f-74cead552cbe.png)

**Comment by devonestes** [comment]
Fixed in #7
